// GET all data
GET http://localhost:5000/api/expenses

###
// GET data by shop
GET http://localhost:5000/api/expenses/shop?shop=K-Market

###
// GET data by category
GET http://localhost:5000/api/expenses/category?category=ruokakauppa

###
// GET data by amount
GET http://localhost:5000/api/expenses/amount?amount=14.20

###
// GET data by date
GET http://localhost:5000/api/expenses/purchase_date?purchase_date=2022-06-01

###
// GET data by month
GET http://localhost:5000/api/expenses/month/6

###
// GET data by id
GET http://localhost:5000/api/expenses/id/1

###
// Add new data
POST http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
    "purchase_date": "2022-07-16",
    "amount": 44.90,
    "shop": "XXL",
    "category": "urheilukauppa"
}

###
// Update data
PUT http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
    "id": 2,
    "purchase_date": "2022-06-07",
    "amount": 29.95,
    "shop": "Lidl",
    "category": "ruokakauppa"
}

###
// Delete data
DELETE http://localhost:5000/api/expenses/id/120