GET http://localhost:5000/api/expenses

###

GET http://localhost:5000/api/expenses?shop=Prisma

###

POST http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
    "purchase_date": "2022-07-3",
    "amount": 17.45,
    "shop": "Prisma",
    "category": "ruokakauppa"
}

###

PUT http://localhost:5000/api/expenses HTTP/1.1
content-type: application/json

{
    "id": 2,
    "purchase_date": "2022-06-07",
    "amount": 29.95,
    "shop": "Lidl",
    "category": "ruokakauppa"
}

###

DELETE http://localhost:5000/api/expenses/3