// GET all data
GET http://final-project-kaisahakola.onrender.com/api/expenses

###
// GET by shop
GET http://final-project-kaisahakola.onrender.com/api/expenses/shop?shop=K-Market

###
// GET data by category
GET http://final-project-kaisahakola.onrender.com/api/expenses/category?category=urheilukauppa

###
// GET data by amount
GET http://final-project-kaisahakola.onrender.com/api/expenses/amount?amount=29.95

###
// GET data by date
GET http://final-project-kaisahakola.onrender.com/api/expenses/purchase_date?purchase_date=2022-07-13

###
// GET data by month
GET http://final-project-kaisahakola.onrender.com/api/expenses/month/7

###
// GET by id
GET http://final-project-kaisahakola.onrender.com/api/expenses/id/1

###
// Add new data
POST http://final-project-kaisahakola.onrender.com/api/expenses HTTP/1.1
content-type: application/json

{
    "purchase_date": "2022-07-14",
    "amount": 38.95,
    "shop": "Intersport",
    "category": "urheilukauppa"
}

###
// Update data
PUT http://final-project-kaisahakola.onrender.com/api/expenses HTTP/1.1
content-type: application/json

{
    "id": 81,
    "purchase_date": "2022-07-03",
    "amount": 29.95,
    "shop": "Prisma",
    "category": "ruokakauppa"
}

###
// Detele data
DELETE http://final-project-kaisahakola.onrender.com/api/expenses/119